[package]
name = "espthen"
version = "0.1.0"
edition = "2021"
authors = ["Robotix_00"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pnet]
version = "0.33.0"

[dependencies.radiotap]
version = "1.3.0"
