[package]
name = "esp_then"
version = "0.1.0"
edition = "2021"
authors = ["Robotix_00"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
